# Generated by Django 6.0.1 on 2026-02-13 19:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Exhibit',
            fields=[
                ('exhibitId', models.AutoField(db_column='exhibitId', primary_key=True, serialize=False)),
                ('title', models.TextField(blank=True, db_column='title', null=True)),
                ('domain', models.TextField(blank=True, db_column='domain', null=True)),
                ('backgroundDeploymentContext', models.TextField(blank=True, db_column='backgroundDeploymentContext', null=True)),
                ('intededUse', models.TextField(blank=True, db_column='intededUse', null=True)),
                ('viewNumber', models.IntegerField(blank=True, db_column='viewNumber', null=True)),
            ],
            options={
                'db_table': 'exhibits',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('userId', models.AutoField(db_column='userId', primary_key=True, serialize=False)),
                ('userLevel', models.IntegerField(db_column='userLevel')),
                ('fName', models.CharField(blank=True, db_column='fName', null=True)),
                ('lName', models.CharField(blank=True, db_column='lName', null=True)),
                ('password', models.CharField(blank=True, db_column='password', null=True)),
                ('totalQuizzPoints', models.IntegerField(blank=True, db_column='totalQuizzPoints', null=True)),
            ],
            options={
                'db_table': 'users',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='ContributingFactors',
            fields=[
                ('contributingFactorId', models.AutoField(db_column='contributingFactorId', primary_key=True, serialize=False)),
                ('dataIssues', models.TextField(blank=True, db_column='dataIssues', null=True)),
                ('designChoices', models.TextField(blank=True, db_column='designChoices', null=True)),
                ('organisationalOrGovernanceIssues', models.TextField(blank=True, db_column='organisationalOrGovernanceIssues', null=True)),
                ('exhibitId', models.ForeignKey(blank=True, db_column='exhibitId', null=True, on_delete=django.db.models.deletion.CASCADE, to='museumApp.exhibit')),
            ],
            options={
                'db_table': 'contributing_factors',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Artefact',
            fields=[
                ('artefactId', models.AutoField(db_column='artefactId', primary_key=True, serialize=False)),
                ('info', models.CharField(blank=True, db_column='info', null=True)),
                ('artefactDate', models.DateField(blank=True, db_column='artefactDate', null=True)),
                ('artefactObjectPath', models.ImageField(db_column='artefactObjectPath', null=True, upload_to='museumProject/museumApp/ArtefactImages/')),
                ('exhibitId', models.ForeignKey(blank=True, db_column='exhibitId', null=True, on_delete=django.db.models.deletion.CASCADE, to='museumApp.exhibit')),
            ],
            options={
                'db_table': 'artefacts',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='AiSystemDescription',
            fields=[
                ('systemDescriptionId', models.AutoField(db_column='systemDescriptionId', primary_key=True, serialize=False)),
                ('systemDescription', models.TextField(blank=True, db_column='systemDescription', null=True)),
                ('systemPurpose', models.TextField(blank=True, db_column='systemPurpose', null=True)),
                ('systemOutputs', models.TextField(blank=True, db_column='systemOutputs', null=True)),
                ('exhibitId', models.ForeignKey(blank=True, db_column='exhibitId', null=True, on_delete=django.db.models.deletion.CASCADE, to='museumApp.exhibit')),
            ],
            options={
                'db_table': 'AI_system_description',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='FailureDescription',
            fields=[
                ('failureDescriptionId', models.AutoField(db_column='failureDescriptionId', primary_key=True, serialize=False)),
                ('whatWentWrong', models.TextField(blank=True, db_column='whatWentWrong', null=True)),
                ('howItWasDetected', models.TextField(blank=True, db_column='howItWasDetected', null=True)),
                ('whatWasAffected', models.TextField(blank=True, db_column='whatWasAffected', null=True)),
                ('exhibitId', models.ForeignKey(blank=True, db_column='exhibitId', null=True, on_delete=django.db.models.deletion.CASCADE, to='museumApp.exhibit')),
            ],
            options={
                'db_table': 'failure_description',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='LessonsLearned',
            fields=[
                ('lessonslearnedId', models.AutoField(db_column='lessonsLearnedId', primary_key=True, serialize=False)),
                ('practicalRecommendations', models.TextField(blank=True, db_column='practicalRecommendations', null=True)),
                ('futureWarnings', models.TextField(blank=True, db_column='futureWarnings', null=True)),
                ('exhibitId', models.ForeignKey(blank=True, db_column='exhibitId', null=True, on_delete=django.db.models.deletion.CASCADE, to='museumApp.exhibit')),
            ],
            options={
                'db_table': 'lessons_learned',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Quizzes',
            fields=[
                ('quizId', models.AutoField(db_column='quizId', primary_key=True, serialize=False)),
                ('quizzDetails', models.TextField(blank=True, db_column='quizzDetails', null=True)),
                ('completionRate', models.IntegerField(blank=True, db_column='completionRate', null=True)),
                ('attemptRate', models.IntegerField(blank=True, db_column='attemptRate', null=True)),
                ('totalQuestionPoints', models.IntegerField(blank=True, db_column='totalQuestionPoints', null=True)),
                ('exhibitId', models.ForeignKey(blank=True, db_column='exhibitId', null=True, on_delete=django.db.models.deletion.CASCADE, to='museumApp.exhibit')),
            ],
            options={
                'db_table': 'quizzes',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='QuizzQuestions',
            fields=[
                ('questionId', models.AutoField(db_column='questionId', primary_key=True, serialize=False)),
                ('question', models.TextField(db_column='question')),
                ('option1', models.TextField(db_column='option1')),
                ('option2', models.TextField(db_column='option2')),
                ('option3', models.TextField(db_column='option3')),
                ('option4', models.TextField(db_column='option4')),
                ('questionAnswer', models.IntegerField(db_column='questionAnswer')),
                ('completionRate', models.IntegerField(blank=True, db_column='completionRate')),
                ('attemptRate', models.IntegerField(blank=True, db_column='attemptRate')),
                ('points', models.IntegerField(blank=True, db_column='points')),
                ('quizId', models.ForeignKey(blank=True, db_column='quizId', on_delete=django.db.models.deletion.CASCADE, to='museumApp.quizzes')),
            ],
            options={
                'db_table': 'quizz_questions',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='BookMarks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exhibitId', models.ForeignKey(blank=True, db_column='exhibitId', on_delete=django.db.models.deletion.CASCADE, to='museumApp.exhibit')),
                ('userId', models.ForeignKey(blank=True, db_column='userId', on_delete=django.db.models.deletion.CASCADE, to='museumApp.users')),
            ],
            options={
                'db_table': 'book_marks',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='AttemptedQuizzes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pointsGained', models.IntegerField(blank=True, db_column='pointsGained')),
                ('attemptDate', models.DateField(blank=True, db_column='attemptDate')),
                ('quizId', models.ForeignKey(blank=True, db_column='quizId', on_delete=django.db.models.deletion.CASCADE, to='museumApp.quizzes')),
                ('userId', models.ForeignKey(blank=True, db_column='userId', on_delete=django.db.models.deletion.CASCADE, to='museumApp.users')),
            ],
            options={
                'db_table': 'attempted_quizzes',
                'managed': True,
            },
        ),
    ]
