# Generated by Django 6.0.1 on 2026-02-09 15:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AttemptedQuizzes',
            fields=[
                ('pk', models.CompositePrimaryKey('userId', 'quizId', blank=True, editable=False, primary_key=True, serialize=False)),
                ('pointsGained', models.IntegerField(blank=True, db_column='pointsGained')),
                ('attemptDate', models.DateField(blank=True, db_column='attemptDate')),
            ],
            options={
                'db_table': 'attempted_quizzes',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='BookMarks',
            fields=[
                ('pk', models.CompositePrimaryKey('userId', 'exhibitId', blank=True, editable=False, primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'book_marks',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Quizzes',
            fields=[
                ('quizId', models.AutoField(db_column='quizId', primary_key=True, serialize=False)),
                ('quizzDetails', models.TextField(blank=True, db_column='quizzDetails')),
                ('completionRate', models.IntegerField(blank=True, db_column='completionRate')),
                ('attemptRate', models.IntegerField(blank=True, db_column='attemptRate')),
                ('totalQuestionPoints', models.IntegerField(blank=True, db_column='totalQuestionPoints')),
            ],
            options={
                'db_table': 'quizzes',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='QuizzQuestions',
            fields=[
                ('questionId', models.AutoField(db_column='questionId', primary_key=True, serialize=False)),
                ('question', models.TextField(db_column='question')),
                ('option1', models.TextField(db_column='option1')),
                ('option2', models.TextField(db_column='option2')),
                ('option3', models.TextField(db_column='option3')),
                ('option4', models.TextField(db_column='option4')),
                ('questionAnswer', models.IntegerField(db_column='questionAnswer')),
                ('completionRate', models.IntegerField(blank=True, db_column='completionRate')),
                ('attemptRate', models.IntegerField(blank=True, db_column='attemptRate')),
                ('points', models.IntegerField(blank=True, db_column='points')),
            ],
            options={
                'db_table': 'quizz_questions',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('userId', models.AutoField(db_column='userId', primary_key=True, serialize=False)),
                ('userLevel', models.IntegerField(db_column='userLevel')),
                ('fName', models.CharField(blank=True, db_column='fName')),
                ('lName', models.CharField(blank=True, db_column='lName')),
                ('password', models.CharField(blank=True, db_column='password')),
                ('totalQuizzPoints', models.IntegerField(blank=True, db_column='totalQuizzPoints')),
            ],
            options={
                'db_table': 'users',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Exhibit',
            fields=[
                ('exhibitId', models.AutoField(db_column='exhibitId', primary_key=True, serialize=False)),
                ('title', models.TextField(blank=True, db_column='title')),
                ('domain', models.TextField(blank=True, db_column='domain')),
                ('backgroundDeploymentContext', models.TextField(blank=True, db_column='backgroundDeploymentContext')),
                ('intededUse', models.TextField(blank=True, db_column='intededUse')),
                ('viewNumber', models.IntegerField(blank=True, db_column='viewNumber')),
            ],
        ),
        migrations.CreateModel(
            name='ContributingFactors',
            fields=[
                ('contributingFactorId', models.AutoField(db_column='contributingFactorId', primary_key=True, serialize=False)),
                ('dataIssues', models.TextField(blank=True, db_column='dataIssues')),
                ('designChoices', models.TextField(blank=True, db_column='designChoices')),
                ('organisationalOrGovernanceIssues', models.TextField(blank=True, db_column='organisationalOrGovernanceIssues')),
                ('exhibitId', models.ForeignKey(blank=True, db_column='exhibitId', on_delete=django.db.models.deletion.CASCADE, to='museumApp.exhibit')),
            ],
            options={
                'db_table': 'contributing_factors',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Artefact',
            fields=[
                ('artefactId', models.AutoField(db_column='artefactId', primary_key=True, serialize=False)),
                ('info', models.CharField(blank=True, db_column='info')),
                ('artefactDate', models.DateField(blank=True, db_column='artefactDate')),
                ('artefactObjectPath', models.TextField(blank=True, db_column='artefactObjectPath')),
                ('exhibitId', models.ForeignKey(db_column='exhibitId', on_delete=django.db.models.deletion.CASCADE, to='museumApp.exhibit')),
            ],
        ),
        migrations.CreateModel(
            name='AiSystemDescription',
            fields=[
                ('systemDescriptionId', models.AutoField(db_column='systemDescriptionId', primary_key=True, serialize=False)),
                ('systemDescription', models.TextField(blank=True, db_column='systemDescription')),
                ('systemPurpose', models.TextField(blank=True, db_column='systemPurpose')),
                ('systemOutputs', models.TextField(blank=True, db_column='systemOutputs')),
                ('exhibit', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='systemDescription', to='museumApp.exhibit')),
            ],
            options={
                'db_table': 'AI_system_description',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='FailureDescription',
            fields=[
                ('failureDescriptioniId', models.AutoField(db_column='failureDescriptionId', primary_key=True, serialize=False)),
                ('whatWentWrong', models.TextField(blank=True, db_column='whatWentWrong')),
                ('howItWasDetected', models.TextField(blank=True, db_column='howItWasDetected')),
                ('whatWasAffected', models.TextField(blank=True, db_column='whatWasAffected')),
                ('exhibit', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='failureDescription', to='museumApp.exhibit')),
            ],
            options={
                'db_table': 'failure_description',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='LessonsLearned',
            fields=[
                ('lessonslearnedId', models.AutoField(db_column='lessonsLearnedId', primary_key=True, serialize=False)),
                ('practicalRecommendations', models.TextField(blank=True, db_column='practicalRecommendations')),
                ('futureWarnings', models.TextField(blank=True, db_column='futureWarnings')),
                ('exhibitId', models.ForeignKey(blank=True, db_column='exhibitId', on_delete=django.db.models.deletion.CASCADE, to='museumApp.exhibit')),
            ],
            options={
                'db_table': 'lessons_learned',
                'managed': True,
            },
        ),
    ]
