# Generated by Django 6.0.2 on 2026-02-16 16:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Exhibit',
            fields=[
                ('exhibitId', models.AutoField(db_column='exhibitId', primary_key=True, serialize=False)),
                ('title', models.TextField(blank=True, db_column='title')),
                ('domain', models.TextField(blank=True, db_column='domain')),
                ('backgroundDeploymentContext', models.TextField(blank=True, db_column='backgroundDeploymentContext')),
                ('intededUse', models.TextField(blank=True, db_column='intededUse')),
                ('viewNumber', models.IntegerField(blank=True, db_column='viewNumber')),
            ],
            options={
                'db_table': 'Exhibit',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='ContributingFactors',
            fields=[
                ('contributingFactorId', models.AutoField(db_column='contributingFactorId', primary_key=True, serialize=False)),
                ('dataIssues', models.TextField(blank=True, db_column='dataIssues')),
                ('designChoices', models.TextField(blank=True, db_column='designChoices')),
                ('organisationalOrGovernanceIssues', models.TextField(blank=True, db_column='organisationalOrGovernanceIssues')),
                ('exhibitId', models.ForeignKey(blank=True, db_column='exhibitId', on_delete=django.db.models.deletion.CASCADE, to='museumApp.exhibit')),
            ],
            options={
                'db_table': 'contributing_factors',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='BookMarks',
            fields=[
                ('pk', models.CompositePrimaryKey('userId', 'exhibitId', blank=True, editable=False, primary_key=True, serialize=False)),
                ('userId', models.ForeignKey(blank=True, db_column='userId', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('exhibitId', models.ForeignKey(blank=True, db_column='exhibitId', on_delete=django.db.models.deletion.CASCADE, to='museumApp.exhibit')),
            ],
            options={
                'db_table': 'book_marks',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Artefact',
            fields=[
                ('artefactId', models.AutoField(db_column='artefactId', primary_key=True, serialize=False)),
                ('info', models.CharField(blank=True, db_column='info', max_length=255)),
                ('artefactDate', models.DateField(blank=True, db_column='artefactDate')),
                ('artefactObjectPath', models.TextField(blank=True, db_column='artefactObjectPath')),
                ('exhibitId', models.ForeignKey(db_column='exhibitId', on_delete=django.db.models.deletion.CASCADE, to='museumApp.exhibit')),
            ],
            options={
                'db_table': 'Artefact',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='AiSystemDescription',
            fields=[
                ('systemDescriptionId', models.AutoField(db_column='systemDescriptionId', primary_key=True, serialize=False)),
                ('systemDescription', models.TextField(blank=True, db_column='systemDescription', null=True)),
                ('systemPurpose', models.TextField(blank=True, db_column='systemPurpose', null=True)),
                ('systemOutputs', models.TextField(blank=True, db_column='systemOutputs', null=True)),
                ('exhibitId', models.OneToOneField(blank=True, db_column='exhibitId', null=True, on_delete=django.db.models.deletion.CASCADE, to='museumApp.exhibit')),
            ],
            options={
                'db_table': 'AI_system_description',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='FailureDescription',
            fields=[
                ('failureDescriptionId', models.AutoField(db_column='failureDescriptionId', primary_key=True, serialize=False)),
                ('whatWentWrong', models.TextField(blank=True, db_column='whatWentWrong')),
                ('howItWasDetected', models.TextField(blank=True, db_column='howItWasDetected')),
                ('whatWasAffected', models.TextField(blank=True, db_column='whatWasAffected')),
                ('exhibitId', models.OneToOneField(blank=True, db_column='exhibitId', null=True, on_delete=django.db.models.deletion.CASCADE, to='museumApp.exhibit')),
            ],
            options={
                'db_table': 'failure_description',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='LessonsLearned',
            fields=[
                ('lessonslearnedId', models.AutoField(db_column='lessonsLearnedId', primary_key=True, serialize=False)),
                ('practicalRecommendations', models.TextField(blank=True, db_column='practicalRecommendations')),
                ('futureWarnings', models.TextField(blank=True, db_column='futureWarnings')),
                ('exhibitId', models.ForeignKey(blank=True, db_column='exhibitId', on_delete=django.db.models.deletion.CASCADE, to='museumApp.exhibit')),
            ],
            options={
                'db_table': 'lessons_learned',
                'managed': True,
            },
        ),
    ]
