# Generated by Django 6.0.1 on 2026-01-30 15:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('museumApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Artefact',
            fields=[
                ('artefactid', models.AutoField(db_column='ArtefactId', primary_key=True, serialize=False)),
                ('info', models.CharField(blank=True, db_column='Info', null=True)),
                ('artefactdate', models.DateField(blank=True, db_column='ArtefactDate', null=True)),
                ('artefactobjectpath', models.TextField(blank=True, db_column='ArtefactObjectPath', null=True)),
                ('exhibitid', models.ForeignKey(db_column='ExhibitId', on_delete=django.db.models.deletion.CASCADE, to='museumApp.exhibit')),
            ],
        ),
    ]
