# Generated by Django 6.0.1 on 2026-02-15 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('museumApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artefact',
            name='info',
            field=models.CharField(blank=True, db_column='info', max_length=255),
        ),
    ]
