# Generated by Django 6.0.3 on 2026-03-20 12:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("museumApp", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Comments",
            fields=[
                (
                    "commentId",
                    models.AutoField(
                        db_column="commentId", primary_key=True, serialize=False
                    ),
                ),
                ("content", models.TextField(blank=True, db_column="content")),
                (
                    "date",
                    models.DateTimeField(auto_now_add=True, db_column="timestamp"),
                ),
                (
                    "isApproved",
                    models.BooleanField(db_column="isApproved", default=False),
                ),
                (
                    "exhibit",
                    models.ForeignKey(
                        blank=True,
                        db_column="exhibitId",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="museumApp.exhibit",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        db_column="userId",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
