# Generated by Django 6.0.1 on 2026-02-16 19:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('museumApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artefact',
            name='exhibitId',
            field=models.OneToOneField(blank=True, db_column='exhibitId', null=True, on_delete=django.db.models.deletion.CASCADE, to='museumApp.exhibit'),
        ),
        migrations.AlterField(
            model_name='contributingfactors',
            name='exhibitId',
            field=models.OneToOneField(blank=True, db_column='exhibitId', null=True, on_delete=django.db.models.deletion.CASCADE, to='museumApp.exhibit'),
        ),
        migrations.AlterField(
            model_name='lessonslearned',
            name='exhibitId',
            field=models.OneToOneField(blank=True, db_column='exhibitId', null=True, on_delete=django.db.models.deletion.CASCADE, to='museumApp.exhibit'),
        ),
    ]
