# Generated by Django 6.0.1 on 2026-02-15 18:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('museumApp', '0002_alter_artefact_info'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AttemptedQuizzes',
        ),
        migrations.DeleteModel(
            name='BookMarks',
        ),
        migrations.DeleteModel(
            name='Quizzes',
        ),
        migrations.DeleteModel(
            name='QuizzQuestions',
        ),
        migrations.DeleteModel(
            name='Users',
        ),
    ]
