# Generated by Django 6.0.3 on 2026-03-20 14:36

from django.db import migrations


def create_groups(apps, schema_editor):
    Group = apps.get_model('auth', 'Group')
    Group.objects.get_or_create(name='Curator')
    Group.objects.get_or_create(name='Visitor')

def delete_groups(apps, schema_editor):
    Group = apps.get_model('auth', 'Group')
    Group.objects.filter(name__in=['Curator', 'Visitor']).delete()


class Migration(migrations.Migration):

    dependencies = [
        ("museumApp", "0002_comments"),
    ]

    operations = [
        migrations.RunPython(create_groups, delete_groups),
    ]