# Generated by Django 6.0.1 on 2026-02-16 20:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('museumApp', '0002_alter_artefact_exhibitid_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artefact',
            name='exhibitId',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='museumApp.exhibit'),
            preserve_default=False,
        ),
    ]
