# Generated by Django 6.0.1 on 2026-01-30 15:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('museumApp', '0002_artefact'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artefact',
            name='exhibitid',
            field=models.ForeignKey(db_column='exhibitid', on_delete=django.db.models.deletion.CASCADE, to='museumApp.exhibit'),
        ),
    ]
