# Generated by Django 6.0.1 on 2026-01-30 15:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('museumApp', '0003_alter_artefact_exhibitid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artefact',
            name='artefactdate',
            field=models.DateField(blank=True, db_column='artefactDate', null=True),
        ),
        migrations.AlterField(
            model_name='artefact',
            name='artefactid',
            field=models.AutoField(db_column='artefactId', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='artefact',
            name='artefactobjectpath',
            field=models.TextField(blank=True, db_column='artefactObjectPath', null=True),
        ),
        migrations.AlterField(
            model_name='artefact',
            name='exhibitid',
            field=models.ForeignKey(db_column='exhibitId', on_delete=django.db.models.deletion.CASCADE, to='museumApp.exhibit'),
        ),
        migrations.AlterField(
            model_name='artefact',
            name='info',
            field=models.CharField(blank=True, db_column='info', null=True),
        ),
        migrations.AlterField(
            model_name='exhibit',
            name='backgrounddeploymentcontext',
            field=models.TextField(blank=True, db_column='backgroundDeploymentContext', null=True),
        ),
        migrations.AlterField(
            model_name='exhibit',
            name='domain',
            field=models.TextField(blank=True, db_column='domain', null=True),
        ),
        migrations.AlterField(
            model_name='exhibit',
            name='exhibitid',
            field=models.AutoField(db_column='exhibitId', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='exhibit',
            name='intededuse',
            field=models.TextField(blank=True, db_column='intededUse', null=True),
        ),
        migrations.AlterField(
            model_name='exhibit',
            name='title',
            field=models.TextField(blank=True, db_column='title', null=True),
        ),
        migrations.AlterField(
            model_name='exhibit',
            name='viewnumber',
            field=models.IntegerField(blank=True, db_column='viewNumber', null=True),
        ),
    ]
