# Generated by Django 6.0.1 on 2026-01-30 16:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('museumApp', '0004_alter_artefact_artefactdate_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='artefact',
            old_name='artefactdate',
            new_name='artefactDate',
        ),
        migrations.RenameField(
            model_name='artefact',
            old_name='artefactid',
            new_name='artefactId',
        ),
        migrations.RenameField(
            model_name='artefact',
            old_name='artefactobjectpath',
            new_name='artefactObjectPath',
        ),
        migrations.RenameField(
            model_name='artefact',
            old_name='exhibitid',
            new_name='exhibitId',
        ),
        migrations.RenameField(
            model_name='exhibit',
            old_name='backgrounddeploymentcontext',
            new_name='backgroundDeploymentContext',
        ),
        migrations.RenameField(
            model_name='exhibit',
            old_name='exhibitid',
            new_name='exhibitId',
        ),
        migrations.RenameField(
            model_name='exhibit',
            old_name='intededuse',
            new_name='intededUse',
        ),
        migrations.RenameField(
            model_name='exhibit',
            old_name='viewnumber',
            new_name='viewNumber',
        ),
    ]
