# Generated by Django 6.0.1 on 2026-01-31 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('museumApp', '0005_rename_artefactdate_artefact_artefactdate_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AiSystemDescription',
            fields=[
                ('systemDescriptionId', models.AutoField(db_column='systemDescriptionId', primary_key=True, serialize=False)),
                ('systemDescription', models.TextField(blank=True, db_column='systemDescription', null=True)),
                ('systemPurpose', models.TextField(blank=True, db_column='systemPurpose', null=True)),
                ('systemOutputs', models.TextField(blank=True, db_column='systemOutputs', null=True)),
            ],
            options={
                'db_table': 'AI_system_description',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='FailureDescription',
            fields=[
                ('failureDescriptioniId', models.AutoField(db_column='failureDescriptionId', primary_key=True, serialize=False)),
                ('whatWentWrong', models.TextField(blank=True, db_column='whatWentWrong', null=True)),
                ('howItWasDetected', models.TextField(blank=True, db_column='howItWasDetected', null=True)),
                ('whatWasAffected', models.TextField(blank=True, db_column='whatWasAffected', null=True)),
            ],
            options={
                'db_table': 'failure_description',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='LessonsLearned',
            fields=[
                ('lessonslearnedId', models.AutoField(db_column='lessonsLearnedId', primary_key=True, serialize=False)),
                ('practicalRecommendations', models.TextField(blank=True, db_column='practicalRecommendations', null=True)),
                ('futureWarnings', models.TextField(blank=True, db_column='futureWarnings', null=True)),
            ],
            options={
                'db_table': 'lessons_learned',
                'managed': False,
            },
        ),
    ]
