# Generated by Django 6.0.1 on 2026-01-31 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('museumApp', '0006_aisystemdescription_failuredescription_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Quizzes',
            fields=[
                ('quizId', models.AutoField(db_column='quizId', primary_key=True, serialize=False)),
                ('quizzDetails', models.TextField(blank=True, db_column='quizzDetails', null=True)),
                ('completionRate', models.IntegerField(blank=True, db_column='completionRate', null=True)),
                ('attemptRate', models.IntegerField(blank=True, db_column='attemptRate', null=True)),
                ('totalQuestionPoints', models.IntegerField(blank=True, db_column='totalQuestionPoints', null=True)),
            ],
            options={
                'db_table': 'quizzes',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('userId', models.AutoField(db_column='userId', primary_key=True, serialize=False)),
                ('userLevel', models.IntegerField(db_column='userLevel')),
                ('fName', models.CharField(blank=True, db_column='fName', null=True)),
                ('lName', models.CharField(blank=True, db_column='lName', null=True)),
                ('password', models.CharField(blank=True, db_column='assword', null=True)),
                ('totalQuizzPoints', models.IntegerField(blank=True, db_column='totalQuizzPoints', null=True)),
            ],
            options={
                'db_table': 'users',
                'managed': False,
            },
        ),
    ]
