# Generated by Django 6.0.1 on 2026-01-31 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('museumApp', '0007_quizzes_users'),
    ]

    operations = [
        migrations.CreateModel(
            name='AttemptedQuizzes',
            fields=[
                ('pk', models.CompositePrimaryKey('userId', 'quizId', blank=True, editable=False, primary_key=True, serialize=False)),
                ('pointsGained', models.IntegerField(blank=True, db_column='pointsGained', null=True)),
                ('attemptDate', models.DateField(blank=True, db_column='attemptDate', null=True)),
            ],
            options={
                'db_table': 'attempted_quizzes',
                'managed': False,
            },
        ),
    ]
