# Generated by Django 6.0.1 on 2026-01-31 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('museumApp', '0008_attemptedquizzes'),
    ]

    operations = [
        migrations.CreateModel(
            name='BookMarks',
            fields=[
                ('pk', models.CompositePrimaryKey('userId', 'exhibitId', blank=True, editable=False, primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'book_marks',
                'managed': False,
            },
        ),
    ]
