# Generated by Django 6.0.1 on 2026-01-31 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('museumApp', '0009_bookmarks'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuizzQuestions',
            fields=[
                ('questionId', models.AutoField(db_column='questionId', primary_key=True, serialize=False)),
                ('question', models.TextField(blank=True, db_column='question', null=True)),
                ('questionAnswer', models.TextField(blank=True, db_column='questionAnswer', null=True)),
                ('completionRate', models.IntegerField(blank=True, db_column='completionRate', null=True)),
                ('attemptRate', models.IntegerField(blank=True, db_column='attemptRate', null=True)),
                ('points', models.IntegerField(blank=True, db_column='points', null=True)),
            ],
            options={
                'db_table': 'quizz_questions',
                'managed': False,
            },
        ),
    ]
