# Generated by Django 6.0.1 on 2026-02-02 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('museumApp', '0010_quizzquestions'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContributingFactors',
            fields=[
                ('contributingFactorId', models.AutoField(db_column='contributingFactorId', primary_key=True, serialize=False)),
                ('dataIssues', models.TextField(blank=True, db_column='dataIssues', null=True)),
                ('designChoices', models.TextField(blank=True, db_column='designChoices', null=True)),
                ('organisationalOrGovernanceIssues', models.TextField(blank=True, db_column='organisationalOrGovernanceIssues', null=True)),
            ],
            options={
                'db_table': 'contributing_factors',
                'managed': False,
            },
        ),
    ]
