# Generated by Django 6.0.1 on 2026-02-09 05:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("museumApp", "0011_contributingfactors"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="aisystemdescription",
            options={"managed": True},
        ),
        migrations.AlterModelOptions(
            name="contributingfactors",
            options={"managed": True},
        ),
        migrations.AlterModelOptions(
            name="failuredescription",
            options={"managed": True},
        ),
        migrations.AlterModelOptions(
            name="lessonslearned",
            options={"managed": True},
        ),
    ]
