# Generated by Django 6.0.1 on 2026-02-09 05:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("museumApp", "0012_alter_aisystemdescription_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="aisystemdescription",
            name="exhibitId",
            field=models.ForeignKey(
                blank=True,
                db_column="exhibitId",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="museumApp.exhibit",
            ),
        ),
        migrations.AddField(
            model_name="contributingfactors",
            name="exhibitId",
            field=models.ForeignKey(
                blank=True,
                db_column="exhibitId",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="museumApp.exhibit",
            ),
        ),
        migrations.AddField(
            model_name="failuredescription",
            name="exhibitId",
            field=models.ForeignKey(
                blank=True,
                db_column="exhibitId",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="museumApp.exhibit",
            ),
        ),
        migrations.AddField(
            model_name="lessonslearned",
            name="exhibitId",
            field=models.ForeignKey(
                blank=True,
                db_column="exhibitId",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="museumApp.exhibit",
            ),
        ),
    ]
