# Generated by Django 6.0.1 on 2026-02-09 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('museumApp', '0013_aisystemdescription_exhibitid_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artefact',
            name='artefactObjectPath',
            field=models.ImageField(db_column='artefactObjectPath', null=True, upload_to='museumProject/museumApp/ArtefactImages/'),
        ),
    ]
